
#spring:
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
      
########## MySQL hibernate properties

hibernate:
    dialect: org.hibernate.dialect.MySQLDialect 
    hbm2ddl.auto: create    
    show_sql: true
    lazy_load: true

db:
  driver: com.mysql.jdbc.Driver   
  jdbcurl: jdbc:mysql://localhost:3306/yqueue   
  dbUsername: root  
  dbPassword: root



#spring.mvc.view.prefix: /
#spring.mvc.view.suffix: .jsp
#spring.jpa.hibernate.ddl-auto=update

# Connection url for the database "netgloo_blog"
#spring.datasource.url = jdbc:mysql://localhost:3306/SecurityTest
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.show-sql=true
# Username and password
#spring.datasource.username = root
#spring.datasource.password = root



